<script src="<?php echo $base_URL ?>/js/medical4u.js"></script>
<script src="<?php echo $base_URL ?>/commons/js/jquery-3.1.1.js"></script>
<script src="<?php echo $base_URL ?>/commons/js/jquery-ui.js"></script>
<script src="<?php echo $base_URL ?>/commons/js/popper.min.js"></script>
<script src="<?php echo $base_URL ?>/commons/js/bootstrap.min.js"></script>
<script src="<?php echo $base_URL ?>/commons/js/jquery.dataTables.js"></script>
<script src="<?php echo $base_URL ?>/commons/js/dataTables.bootstrap4.min.js"></script>
<script src="<?php echo $base_URL ?>/commons/js/fa-solid.js"></script>
<script src="<?php echo $base_URL ?>/commons/js/fontawesome-all.js"></script>
<script src="<?php echo $base_URL ?>/js/validate.js"></script>
<script src="<?php echo $base_URL ?>/js/<?php echo $_SESSION['page_name'] ?>.js"></script>
