CREATE DATABASE Medical_System;
USE Medical_System;

CREATE TABLE Locations (
    LOC_ID INT UNSIGNED AUTO_INCREMENT,
    CITY VARCHAR(20) NOT NULL,
    STATE CHAR(2) NOT NULL,
    ADDRESS VARCHAR(30) NOT NULL,
    PRIMARY KEY (LOC_ID)
    );

CREATE TABLE Specialties (
    SPECIALTIES_ID INT UNSIGNED AUTO_INCREMENT,
    SPECIALTIES_NAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (SPECIALTIES_ID)
    );

CREATE TABLE Doctors (
    DOC_ID INT UNSIGNED AUTO_INCREMENT,
    LOC_ID INT,
    SPECIALTIES_ID INT,
    DOC_NAME VARCHAR(30) NOT NULL,
    DOC_PHONE CHAR(15) NOT NULL,
    PRIMARY KEY (DOC_ID),
    CONSTRAINT FK_DOCTORS_LOCATION FOREIGN KEY (LOC_ID)
    				REFERENCES Locations(LOC_ID),
    CONSTRAINT FK_DOCTORS_SPECIALTIES FOREIGN KEY (SPECIALTIES_ID)
	 				REFERENCES Specialties(SPECIALTIES_ID)
    );

CREATE TABLE Rooms (
    ROOM_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    LOC_ID INT,
    CONSTRAINT FK_ROOM_LOCATION FOREIGN KEY(LOC_ID)
	 				REFERENCES Locations(LOC_ID),
    ROOM_NUMBER INT(6) NOT NULL
    );

CREATE TABLE Patients (
    PATIENT_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PATIENT_NAME VARCHAR(30) NOT NULL,
    DOC_ID INT,
    PATIENT_DATA_BIRTH DATE NOT NULL,
    PATIENT_BLOOD_TYPE CHAR(10) NOT NULL,
    CONSTRAINT FK_PATIENTS_DOCTOR FOREIGN KEY (DOC_ID)
	 				REFERENCES Doctors(DOC_ID)
    );

CREATE TABLE Schedule (
    SCHEDULE_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    SCHEDULE_DATE TIMESTAMP,
    PATIENT_ID INT,
    DOC_ID INT,
    ROOM_ID INT,
    CONSTRAINT FK_SCHEDULE_PATIENT FOREIGN KEY (PATIENT_ID)
	 				REFERENCES Patients(PATIENT_ID),
    CONSTRAINT FK_SCHEDULE_DOCTOR FOREIGN KEY (DOC_ID)
	 				REFERENCES Doctors(DOC_ID),
    CONSTRAINT FK_SCHEDULE_ROOM FOREIGN KEY (ROOM_ID)
	 				REFERENCES Rooms(ROOM_ID)
    );

CREATE TABLE Users (
    USER_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(40) NOT NULL,
    USER_PASSWORD VARCHAR(40) NOT NULL,
    USER_TYPE VARCHAR(40) NOT NULL
    );
