CREATE DATABASE MEDICAL4U;
USE MEDICAL4U;

CREATE TABLE Locations (
    LOC_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CITY VARCHAR(20) NOT NULL,
    STATE CHAR(2) NOT NULL,
    ADDRESS VARCHAR(30) NOT NULL
    )ENGINE=InnoDB;

CREATE TABLE Specialties (
    SPECIALTIES_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SPECIALTIES_NAME VARCHAR(30) NOT NULL
    )ENGINE=InnoDB;

CREATE TABLE Doctors (
    DOC_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOC_ID INT NOT NULL,
    SPECIALTIES_ID INT NOT NULL,
    DOC_NAME VARCHAR(30) NOT NULL,
    DOC_PHONE VARCHAR(15) NOT NULL,
	FOREIGN KEY FK_DOCTORS_LOCATION(LOC_ID)
    				REFERENCES Locations(LOC_ID),
	FOREIGN KEY FK_DOCTORS_SPECIALTIES(SPECIALTIES_ID)
	 				REFERENCES Specialties(SPECIALTIES_ID)
   ON UPDATE CASCADE
   ON DELETE RESTRICT
    )ENGINE=InnoDB;


CREATE TABLE Rooms (
    ROOM_ID INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOC_ID INT NOT NULL,
    ROOM_NUMBER INT(6) NOT NULL,
	FOREIGN KEY FK_ROOM_LOCATION(LOC_ID)
	 				REFERENCES Locations(LOC_ID)
   ON UPDATE CASCADE
   ON DELETE RESTRICT
    )ENGINE=InnoDB;

CREATE TABLE Patients (
    PATIENT_ID INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PATIENT_NAME VARCHAR(30) NOT NULL,
    DOC_ID INT NOT NULL,
    PATIENT_DATA_BIRTH DATE NOT NULL,
    PATIENT_BLOOD_TYPE CHAR(10) NOT NULL,
	FOREIGN KEY FK_PATIENTS_DOCTOR(DOC_ID)
	 				REFERENCES Doctors(DOC_ID)
   ON UPDATE CASCADE
   ON DELETE RESTRICT
    )ENGINE=InnoDB;

CREATE TABLE Users (
    USER_ID INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(40) NOT NULL,
    USER_PASSWORD VARCHAR(40) NOT NULL,
    USER_TYPE VARCHAR(40) NOT NULL
    )ENGINE=InnoDB;

CREATE TABLE Schedules (
    SCHEDULE_ID INT(6) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SCHEDULE_DATE DATE NOT NULL,
    PATIENT_ID INT NOT NULL,
    DOC_ID INT NOT NULL,
    ROOM_ID INT NOT NULL,
    SCHEDULE_NOTES VARCHAR(50),
	FOREIGN KEY FK_SCHEDULE_PATIENT(PATIENT_ID)
	 				REFERENCES Patients(PATIENT_ID),
	FOREIGN KEY FK_SCHEDULE_DOCTOR(DOC_ID)
	 				REFERENCES Doctors(DOC_ID),
	FOREIGN KEY FK_SCHEDULE_ROOM(ROOM_ID)
	 				REFERENCES Rooms(ROOM_ID)
   ON UPDATE CASCADE
   ON DELETE RESTRICT
    )ENGINE=InnoDB;
