-- CREATE DATABASE MEDICAL4U;
USE MEDICAL4U;

INSERT INTO UserGroups (GROUP_NAME, DESCRIPTION)VALUES 
('SysAdmin', 'System Administrator'),
('Admin', 'Administrator'),
('User', 'Employee');


INSERT INTO Departments (DEPT_NAME, DESCRIPTION) VALUES 
('Advanced Practice', 'Take your skills to the next level. Enjoy greater autonomy and opportunity.'),
('Allied Health', 'Make a difference in delivering positive patient outcomes in a variety of clinical disciplines – from rehab and imaging to laboratories and pharmacy and everything in between.'),
('Home Health Aides', 'Help bring our exceptional, compassionate care right to the patient’s home.'),
('Information Technology', 'Drive exciting innovations in advanced clinical and IT systems.'),
('Laboratory', 'Bring your precision, accuracy and skill to the largest lab in metro New York.'),
('Professional / Technical / Support', 'You can provide key support in a wide range of clinical and non-clinical areas like, accounting, HR and marketing to nursing support, housekeeping and maintenance.'),
('Nursing', 'As a cornerstone of the health care team, you’ll offer the very best care to your patients in award winning hospitals and facilities.'),
('Physicians', 'Elevate your practice with some of the world’s most respected and renowned doctors.'),
('Research', 'Discover tomorrow’s medical breakthroughs working at the Feinstein Institute for Medical Research.');


INSERT INTO Users (FIRST_NAME, LAST_NAME, DEPT_ID, USER_NAME, USER_PASSWORD, USER_GROUP) VALUES
('sysadmin', 'sysadmin', 4, 'admin', SHA('sysadmin1234'), 1),
('user1', 'user1', 8, 'user1', SHA('user11234'), 3),
('user2', 'user2', 8, 'user2', SHA('user21234'), 3),
('admin', 'admin', 6, 'admin', SHA('admin1234'), 2);   

 INSERT INTO STATES (`CODE`, `NAME`) VALUES
('AL', 'Alabama'),
('AK', 'Alaska'),
('AS', 'American Samoa'),
('AZ', 'Arizona'),
('AR', 'Arkansas'),
('CA', 'California'),
('CO', 'Colorado'),
('CT', 'Connecticut'),
('DE', 'Delaware'),
('DC', 'District Of Columbia'),
('FM', 'Federated States Of Micronesia'),
('FL', 'Florida'),
('GA', 'Georgia'),
('GU', 'Guam'),
('HI', 'Hawaii'),
('ID', 'Idaho'),
('IL', 'Illinois'),
('IN', 'Indiana'),
('IA', 'Iowa'),
('KS', 'Kansas'),
('KY', 'Kentucky'),
('LA', 'Louisiana'),
('ME', 'Maine'),
('MH', 'Marshall Islands'),
('MD', 'Maryland'),
('MA', 'Massachusetts'),
('MI', 'Michigan'),
('MN', 'Minnesota'),
('MS', 'Mississippi'),
('MO', 'Missouri'),
('MT', 'Montana'),
('NE', 'Nebraska'),
('NV', 'Nevada'),
('NH', 'New Hampshire'),
('NJ', 'New Jersey'),
('NM', 'New Mexico'),
('NY', 'New York'),
('NC', 'North Carolina'),
('ND', 'North Dakota'),
('MP', 'Northern Mariana Islands'),
('OH', 'Ohio'),
('OK', 'Oklahoma'),
('OR', 'Oregon'),
('PW', 'Palau'),
('PA', 'Pennsylvania'),
('PR', 'Puerto Rico'),
('RI', 'Rhode Island'),
('SC', 'South Carolina'),
('SD', 'South Dakota'),
('TN', 'Tennessee'),
('TX', 'Texas'),
('UT', 'Utah'),
('VT', 'Vermont'),
('VI', 'Virgin Islands'),
('VA', 'Virginia'),
('WA', 'Washington'),
('WV', 'West Virginia'),
('WI', 'Wisconsin'),
('WY', 'Wyoming');


INSERT INTO SPECIALTIES (SPECIALTIES_NAME) VALUES
('Anesthesiology'),
('Cardiothoracic Surgery'),
('Colorectal Surgery'),
('Cosmetic and Reconstructive Surgery'),
('Dermatology'),
('ENT'),
('Emergency Medicine'),
('Family Practice'),
('General Surgery'),
('Gynecologic Oncology'),
('Hand Surgeons'),
('Hip Surgeons'),
('Knee Surgeons'),
('Maternal-Fetal Medicine (MFM)'),
('Neurology'),
('Neurosurgery'),
('Obstetrics & Gynecology (Ob/Gyn)'),
('Ophthalmology'),
('Optometrists'),
('Orthopedic Oncology'),
('Orthopedic Surgery'),
('Pathology'),
('Pediatrics'),
('Physical Medicine and Rehab (PM & R)'),
('Podiatrists'),
('Psychiatry'),
('Psychologists/Counselors'),
('Radiation Oncology'),
('Radiology'),
('Reproductive Endocrinology'),
('Shoulder Surgeons'),
('Spine Surgeons'),
('Sports Medicine'),
('Surgical Endocrinology'),
('Surgical Oncology'),
('Transplant Surgery'),
('Trauma Surgery'),
('Urogynecology'),
('Urology'),
('Vascular Surgery');


INSERT INTO Locations (LOC_NAME, CITY, STATE_ID, ADDRESS, ZIP) VALUES
('NYU Langone Medical Associates', 'New York', 37, '196 Canal St', '10013'),
('NewYork-Presbyterian Lower', 'New York', 37, '170 William St', '10038'),
('Long Isand College Hospital', 'Brooklyn', 37, '339 Hicks St', '11201'),
('Brookyn Hospital Center-Downtown', 'Brooklyn', 37, '121 Dekalb Ave', '11201'),
('Mount Sinai Queens', 'Long Island City', 37, '25-10 30th Ave', '11102'),
('NYC Health Hospital-Elmhurst', 'Elmhurst', 37, '79-01 Broadway', '11373'),
('Long Island Jewish Forest Hills', 'Forest Hills', 37, '102-01 66th Rd', '11375'),
('Northwell Health', 'Queens', 37, '270-05 76th Ave', '11040');


INSERT INTO Rooms (LOC_ID, ROOM_NUMBER) VALUES
(1, '1A'),
(1, '1B'),
(1, '1C'),
(1, '1D'),
(1, '1E'),
(2, '201'),
(2, '301'),
(3, '401'),
(3, '402'),
(3, '403'),
(3, '404'),
(4, '102-A'),
(4, '102-B'),
(4, '102-C');



INSERT INTO Doctors (DOC_NAME, DOC_PHONE, SUFFIX) VALUES 
-- ('Michael Overby', '(516) 569-4709', 'MD'),
('Martin Blaser', '(646) 501-4386', 'MD'),
('Jose U Scher', '(646) 501-7400', 'MD'),
('John G. Golfinos', '(212) 263-2950', 'MD'),
('Alon Mogilner', '(212) 263-2607', 'MD, PhD'),
('Sunil P. Malhotra', '(973) 926-3500', 'MD'),
('Nada G. Abou-Fayssal', '(718) 630-8600', 'MD'),
('Kirk A. Campbell', '(212) 513-7711', 'MD'),
('Alisa Altman', '(631) 425-2110', 'MD'),
('Bruce Gerberg', '(631) 425-2110', 'MD'),
('Dina M. DiMaggio', '(718) 857-5500', 'MD'),
('Erich G. Anderer', '(718) 630-6580', 'MD'),
('Joseph W. Dryer', '(646) 501-7200', 'MD'),
('Yong H. Kim', '(212) 427-3986', 'MD');


INSERT INTO DoctorLocations (DOC_ID, LOC_ID) VALUES
(1, 1),
(1, 4),
(1, 5);


INSERT INTO DoctorSpecialties (DOC_ID, SPECIALTIES_ID) VALUES
(1, 1), (1, 3), (1, 5);


INSERT INTO BloodTypes (BLOOD_TYPE_NAME) VALUES
('Unknown'), ('RH+ A'), ('RH- A'), ('RH+ B'), ('RH- B'), ('RH+ AB'), ('RH- AB'), ('RH+ O'), ('RH- O');

INSERT INTO Providers (PROVIDER) VALUES 
('Aetna'), 
('AmeriHealth'), 
('Anthem Blue Cross Blue Shield'), 
('Assurant Health'), 
('Blue Cross Blue Shield'), 
('Blue Cross Blue Shield Association'), 
('Capital District Physicians Health Plan'), 
('CareFirst Blue Cross Blue Shield'), 
('CHA Health'), 
('Cigna'), 
('Coventry Health Care'), 
('Destiny Health'), 
('Easy Choice'), 
('Emblemhealth'), 
('Empire Blue Cross Blue Shield'), 
('Excellus Blue Cross Blue Shield'), 
('Fallon Community Health Plan'), 
('Fidelis Health Care Insurance'), 
('Fortis Health'), 
('Golden Rule'), 
('Group Health Cooperative'), 
('Group Health Incorporated (GHI)'), 
('Harvard Pilgrim'), 
('Health Net'), 
('Health Now BlueCross BlueShield of NorthWestern, NY'), 
('Health Now dba BlueShield of NorthEastern NY'), 
('Health Partners'), 
('Health Plan of Nevada'), 
('Health Republic Insurance of NY'), 
('Healthfirst Health Insurance New York'), 
('HealthSpring'), 
('HIP Health Plan of New York'), 
('Horizon Blue Cross Blue Shield'), 
('Horizon Healthcare NY'), 
('Humana'), 
('Independence Blue Cross'), 
('Independent Health'), 
('Kaiser Permanente'), 
('LifeWise Health Plans'), 
('Medica'), 
('Medical Mutual of Ohio'), 
('MetroPlus Health Plan New York'), 
('Midwest Security'), 
('Monumental Life'), 
('MVP (Mohawk Valley Physicians Health Plan)'), 
('Oscar Health Insurance Plan For New York'), 
('Oxford Health Plans'), 
('PacifiCare Health Systems'), 
('Premera Blue Cross Blue Shield'), 
('Principal Life Insurance Company'), 
('QualChoice'), 
('Regence Blue Cross Blue Shield'), 
('Today’s Option [American’s Progressive] Health Insurance'), 
('Tufts Health Plan'), 
('UniCare'), 
('United Health Insurance for New York'), 
('Univera'), 
('Vista Health Plan'), 
('Wellmark Blue Cross and Blue Shield');
