-- generally, state field would be used as reference
CREATE TABLE States (
	STATE_ID INT(2) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	STATE_NAME VARCHAR(20) NOT NULL,
    STATE_CODE CHAR(2) NOT NULL 
);

CREATE TABLE Locations (
    LOC_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STATE_ID INT NOT NULL,
    CITY VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    CONSTRAINT FK_State_ID_in_Locations FOREIGN KEY (STATE_ID) REFERENCES States(STATE_ID)  ON DELETE CASCADE
);

CREATE TABLE Specialties (
    SPECIALTIES_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SPECIALTIES_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE Doctors (
    DOC_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DOC_FNAME VARCHAR(30) NOT NULL,
    DOC_LNAME VARCHAR(30) NOT NULL,
    DOC_PHONE VARCHAR(15) NULL
);

-- some doctors can have multiple locations.
CREATE TABLE Doctors_Locations (
	DOC_LOC_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DOC_ID INT(6) UNSIGNED NOT NULL,
    LOC_ID INT(6) UNSIGNED NOT NULL,
    CONSTRAINT FK_DOC_ID_in_Doc_Locations FOREIGN KEY (DOC_ID) REFERENCES Doctors(DOC_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LOC_ID_in_Doc_Locations FOREIGN KEY (LOC_ID) REFERENCES Locations(LOC_ID) ON DELETE CASCADE
 );
 
 -- some doctors can have multiple speicalties.
 CREATE TABLE Doctors_Specialties (
    DOC_SPECIALTIES_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DOC_ID INT(6) UNSIGNED NOT NULL,
    SPECIALTIES_ID INT(6) UNSIGNED NOT NULL,
    CONSTRAINT FK_DOC_ID_in_Doctors_Specialties FOREIGN KEY (DOC_ID) REFERENCES Doctors(DOC_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SPECIALTIES_ID_in_Doctors_Specialties FOREIGN KEY (SPECIALTIES_ID) REFERENCES Specialties(SPECIALTIES_ID) ON DELETE CASCADE
 );
 

 CREATE TABLE Rooms (
    ROOM_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    LOC_ID INT(6) UNSIGNED NOT NULL,
    ROOM_NUMBER INT(6) NOT NULL,
    CONSTRAINT FK_LOC_ID_in_Rooms FOREIGN KEY (LOC_ID) REFERENCES Locations(LOC_ID) ON DELETE CASCADE
);
 
 -- reference data
 CREATE TABLE Blood_Types (
	BLOOD_TYPE_ID INT(2) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    BLOOD_TYPE VARCHAR(3) NOT NULL
 );
 
 CREATE TABLE Patients (
    PATIENT_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PATIENT_FNAME VARCHAR(30) NOT NULL,
    PATIENT_LNAME VARCHAR(30) NOT NULL,
    PATIENT_DOB DATE NOT NULL,
    PATIENT_PHONE VARCHAR(15) NULL, 
    BLOOD_TYPE_ID INT(2) UNSIGNED NOT NULL,
    CONSTRAINT FK_BLOOD_TYPE_ID_in_Patients FOREIGN KEY (BLOOD_TYPE_ID) REFERENCES Blood_Types(BLOOD_TYPE_ID) ON DELETE CASCADE
);
 
 CREATE TABLE Schedules (
    SCHEDULE_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SCHEDULE_DATE DATE NOT NULL,
    PATIENT_ID INT(6) UNSIGNED NOT NULL,
    DOC_ID INT(6) UNSIGNED NOT NULL,
    ROOM_ID INT(6) UNSIGNED NOT NULL,
    CONSTRAINT FK_PATIENT_ID_in_Schedules FOREIGN KEY (PATIENT_ID) REFERENCES Patients(PATIENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DOC_ID_in_Schedules FOREIGN KEY (DOC_ID) REFERENCES Doctors(DOC_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ROOM_ID_in_Schedules FOREIGN KEY (ROOM_ID) REFERENCES Rooms(ROOM_ID) ON DELETE CASCADE
);
 
 -- reference data
 CREATE TABLE User_Types (
	USER_TYPE_ID INT(2) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_TYPE VARCHAR(10) NOT NULL
 );
 
 CREATE TABLE Users (
    USER_ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(40) NOT NULL,
    USER_FNAME VARCHAR(30) NOT NULL,
    USER_LNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(40) NOT NULL,
    USER_TYPE_ID INT(2) UNSIGNED NOT NULL,
    LOC_ID INT(6) UNSIGNED NOT NULL,
    CONSTRAINT FK_USER_TYPE_ID_in_Users FOREIGN KEY (USER_TYPE_ID) REFERENCES User_Types(USER_TYPE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LOC_ID_in_Users FOREIGN KEY (LOC_ID) REFERENCES Locations(LOC_ID) ON DELETE CASCADE
);
 
